append_CanoNDPointToSdrPoint – Seeder
append_CanoNDPointToSdrPoint Subroutine
12 statements
Source File
public subroutine append_CanoNDPointToSdrPoint(canopoint, pntArray, spaObjArray, attr_pos)
This routine convert canonical point to seeder point array
Arguments
Type Intent Optional Attributes Name
type(tem_point_type), intent(in) :: canopoint
canonical point object type
type(grw_pointarray_type), intent(inout) :: pntArray
growing array of points
type(grw_spatialObjArray_type), intent(inout) :: spaObjArray
growing array of geometrical objects.
integer, intent(in) :: attr_pos
spatial object type
Calls
Called by
Call graph
append_canondpointtosdrpoint calls append
sdr_load_canonicalnd calls append_canondpointtosdrpoint
sdr_load_geom_table_single calls sdr_load_canonicalnd
sdr_load_geom_table calls sdr_load_geom_table_single
sdr_load_spatialobject_single calls sdr_load_geom_table