append_CanoNDPlaneToTriangle – Seeder
append_CanoNDPlaneToTriangle Subroutine
15 statements
Source File
public subroutine append_CanoNDPlaneToTriangle(plane, triArray, spaObjArray, attr_pos)
This routine convert plane to triangle and add triangle to growing array and add position of triangle into spatialObj%primitive_position
Arguments
Type Intent Optional Attributes Name
type(tem_plane_type), intent(in) :: plane
canonical plane geometry object type
type(grw_trianglearray_type), intent(inout) :: triArray
growing array of triangles
type(grw_spatialObjArray_type), intent(inout) :: spaObjArray
growing array of geometrical objects.
integer, intent(in) :: attr_pos
spatial object type
Calls
Called by
Call graph
append_canondplanetotriangle calls append
append_canondboxtotriangle calls append_canondplanetotriangle
sdr_load_canonicalnd calls append_canondplanetotriangle, append_canondboxtotriangle
sdr_load_geom_table_single calls sdr_load_canonicalnd
sdr_load_geom_table calls sdr_load_geom_table_single
sdr_load_spatialobject_single calls sdr_load_geom_table