create_target – Seeder
create_target Subroutine
180 statements
Source File
public subroutine create_target(node_pos, proto, geometry, leVal, meshUniverse, header, temData)
Routine to create an element with subelement resolution.
This routine is used to define a target element, that is a node, that reached its final level, but contains boundaries, that are to be resolved on a subelement basis. For the treelmesh, this is just a normal element with additional information attached to it. That additional information is covered by a property. For the actual information in the subelement resolution, the children of the target node need to be considered. We use a separate routine for this case, as it is ensured, that this element never will be refined, due to adjacent boundaries. (Any such refinement was already done during the building of the protoTree). Also we will ignore Q-Value complications here for the identification of boundaries. If subelement resolution is active, no Q-Values might be used and the other way around.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: node_pos
Position of leaf in the preliminary tree
type(sdr_protoTree_type), intent(in) :: proto
preliminary tree
type(sdr_geometry_type), intent(in) :: geometry
contains all geometrical objects
type(levelValues_type), intent(in) :: leVal
level value of parent node
type(treelmesh_type), intent(inout) :: meshUniverse
contains bounding cube information
type(sdr_confHead_type), intent(in) :: header
Configuration header.
type(sdr_temData_type), intent(inout) :: temData
Data for the final mesh.
Calls
Called by
Call graph
create_target calls append, bc_color_id, newunit, ply_convertfromoversample, ply_poly_project_n2m, positionofval, sdr_color_points, sdr_find_periodic_neighbor, sdr_neighbor_in_proto, sdr_bitfieldcolors, sdr_color_log2char, sdr_nodeprop_btest, tem_CoordOfId, tem_abort, val
sdr_color_points calls sdr_nodeprop_btest, val
sdr_find_periodic_neighbor calls sdr_nodeprop_btest, tem_CoordOfId, tem_abort, val, kindpos, gettreeidposofcoord, needcalcqvalbybcid, projectveconplane, sdr_qvalbynode, sdr_truncate_qval, tem_BaryOfId, tem_CoordOfReal, tem_IdOfCoord
sdr_neighbor_in_proto calls positionofval, tem_IdOfCoord, tem_ParentOf
gettreeidposofcoord calls positionofval, sdr_nodeprop_btest, tem_CoordOfReal, tem_IdOfCoord
needcalcqvalbybcid calls val, kindpos
sdr_qvalbynode calls val, fraction_PointLine, intersect_RayTriangle
sdr_truncate_qval calls sdr_nodeprop_btest
traverse_tree calls create_target, traverse_tree
sdr_proto2treelm calls traverse_tree
seeder calls sdr_proto2treelm