flood_periphery – Seeder
flood_periphery Subroutine
62 statements
Source File
private subroutine flood_periphery(proto, geometry, meshUniverse)
This routine loops over all intersected with geoemtry nodes and fluidify some node according to the following rule:\n 1. one of its link does noe intersect with any geometry that requires qVal 2. it has fluid neighbor on that direction. i.e. it is wet in that side. Jiaxing Qi
Todo
HK: works for single color only right now! (qvalues are only computed for first color, need to think about what to do for multiple colors.)
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(inout) :: proto
The proto tree description with all the data enabling the flooding.
type(sdr_geometry_type), intent(in) :: geometry
Description of geometric objects.
type(treelmesh_type), intent(in) :: meshUniverse
treelmesh contains bounding cube info
Calls
Called by
Call graph
flood_periphery calls flood_periphery_diagonal, needcalcqvalbybcid, needflddglbybcid, sdr_qvalbynode, sdr_mark_floodnode, tem_BaryOfId, tem_ElemSize, tem_log, tem_toStr, val
flood_periphery_diagonal calls sdr_mark_floodnode, val, sdr_neighbor_in_proto, tem_CoordOfId
needcalcqvalbybcid calls val, kindpos
needflddglbybcid calls val, kindpos
sdr_qvalbynode calls val, fraction_PointLine, intersect_RayTriangle
sdr_neighbor_in_proto calls positionofval, tem_IdOfCoord, tem_ParentOf
sdr_flood_tree calls flood_periphery
seeder calls sdr_flood_tree