getNormal – Seeder
getNormal Function
77 statements
Source File
private function getNormal(geometry, elemBary, node, node_pos, bcid) result(normal)
Obtain the surface normal of the chosen boundary if the boundary has store_normal set. Otherwise a null vector is returned.
Arguments
Type Intent Optional Attributes Name
type(sdr_geometry_type), intent(in) :: geometry
real(kind=rk), intent(in) :: elemBary(3)
type(sdr_node_type), intent(in) :: node
integer, intent(in) :: node_pos
integer, intent(in) :: bcid
Return Value real(kind=rk), (3)
Calls
Called by
Call graph
getnormal calls append, destroy, init, kindpos, mrgrnk, tem_triangle_normal_proximity, val
sdr_identify_boundary calls getnormal
proto2treelm calls sdr_identify_boundary
traverse_tree calls proto2treelm, traverse_tree
sdr_proto2treelm calls traverse_tree