getTreeIDPosOfCoord – Seeder
getTreeIDPosOfCoord Function
21 statements
Source File
private function getTreeIDPosOfCoord(coordReal, mesh, minLevel, maxLevel, leafLevel, leafTreeID, proto) result(pos)
This function returns the position of treeID of given coordReal in the the given mesh Start from minLevel which is the level of neighbor and find the treeID which is a leaf in protoTree
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: coordReal(3)
type(treelmesh_type), intent(in) :: mesh
Mesh contain geometry universe (bounding cube) info
integer, intent(in) :: minLevel
minlevel
integer, intent(in) :: maxLevel
maxlevel
integer, intent(out) :: leafLevel
level in which leaf node is found
integer(kind=long_k), intent(inout) :: leafTreeID
type(sdr_protoTree_type), intent(in) :: proto
preliminary tree
Return Value integer
position of treeID in proto tree
Calls
Called by
Call graph
gettreeidposofcoord calls positionofval, sdr_nodeprop_btest, tem_CoordOfReal, tem_IdOfCoord
sdr_find_periodic_neighbor calls gettreeidposofcoord
create_target calls sdr_find_periodic_neighbor
getbcid_and_calcqval calls sdr_find_periodic_neighbor
sdr_identify_boundary calls getbcid_and_calcqval
traverse_tree calls create_target, traverse_tree
proto2treelm calls sdr_identify_boundary
sdr_proto2treelm calls traverse_tree