is_intersecting – Seeder
is_intersecting Function
33 statements
Source File
public function is_intersecting(cube, geometry, obj_pos) result(intersects)
Test the intersection between the given cube and the object specified by obj_pos.
This test obviously depends on the kind of object to intersect, thus a select case has to be used. Alternatively we might think of deploying function pointers.
Arguments
Type Intent Optional Attributes Name
type(tem_cube_type), intent(in) :: cube
type(sdr_geometry_type), intent(in) :: geometry
integer, intent(in) :: obj_pos
Return Value logical
Calls
Called by
Call graph
is_intersecting calls sdr_periodicplanecubeoverlap, sdr_spacerinterwovencubeoverlap, tem_boxCubeOverlap, tem_cylinderCubeOverlap, tem_ellipsoidCubeOverlap, tem_lineCubeOverlap, tem_pointCubeOverlap, tem_sphereCubeOverlap, tem_triangleCubeOverlap, val
create_children calls is_intersecting
inherit_intersectedobject calls is_intersecting
sdr_build_prototree calls create_children
sdr_inherit_distancerefineobject calls inherit_intersectedobject
sdr_refine_leaf calls inherit_intersectedobject
seeder calls sdr_build_prototree, sdr_inherit_distancerefineobject, sdr_refine_leaf