load_single_fill – Seeder
load_single_fill Subroutine
36 statements
Source File
public subroutine load_single_fill(fills, conf, parent, pos)
Load the value fill definition for a single color.
The filling information has to be provided as a table with the label of the color, the fill value to use, where the color is present and the void value for the rest of the domain: \code{.lua} { label = 'colA', fill = 1.0, void = 0.0 }, \endcode
Defaults are: fill=1.0, void=0.0. Note that the keys can be left out, and assignment by position is possible.
Arguments
Type Intent Optional Attributes Name
type(sdr_subres_fills_type), intent(inout) :: fills
Value definitions for individual colors.
type(flu_State) :: conf
Handle for the Lua script.
integer, intent(in) :: parent
Parent table, within which to open the fills table.
integer, intent(in) :: pos
Position in the table of fills to load.
Calls
Called by
Call graph
load_single_fill calls aot_get_val, aot_table_close, aot_table_open, sdr_subres_fills_add, tem_abort
sdr_subres_fills_add calls append, upper_to_lower
sdr_subres_fills_load calls load_single_fill
sdr_subresolution_load calls sdr_subres_fills_load
sdr_load_config calls sdr_subresolution_load
seeder calls sdr_load_config