needCalcQValByBCID – Seeder
needCalcQValByBCID Function
12 statements
Source File
public function needCalcQValByBCID(attribute, bcid) result(calc_qVal)
This routine checks if a boundary need calc qVal for a given BCID It is used in identify_boundary routine
Arguments
Type Intent Optional Attributes Name
type(sdr_attrList_type), intent(in) :: attribute
integer, intent(in) :: bcid
Return Value logical
Calls
Called by
Call graph
needcalcqvalbybcid calls kindpos, val
flood_periphery calls needcalcqvalbybcid
getbcid_and_calcqval calls needcalcqvalbybcid, sdr_find_periodic_neighbor
sdr_find_periodic_neighbor calls needcalcqvalbybcid
sdr_identify_boundary calls needcalcqvalbybcid, getbcid_and_calcqval
create_target calls sdr_find_periodic_neighbor
proto2treelm calls sdr_identify_boundary
sdr_flood_tree calls flood_periphery
traverse_tree calls create_target, proto2treelm, traverse_tree
seeder calls sdr_flood_tree
sdr_proto2treelm calls traverse_tree