ply_init_l2p – Seeder
ply_init_l2p Subroutine
57 statements
Source File
public subroutine ply_init_l2p(l2p, header, degree)
Initialize the transformations via L2 projections.
Arguments
Type Intent Optional Attributes Name
type(ply_l2p_type), intent(out) :: l2p
type(ply_l2p_header_type), intent(in) :: header
integer, intent(in) :: degree
Calls
Call graph
ply_init_l2p calls ply_legendre_1d, ply_scalprodleg, ply_gausslegpoints, ply_lagrange_1d, ply_lagrange_define, tem_abort
ply_lagrange_1d calls ply_lagrange_mode_at