projectVecOnPlane – Seeder
projectVecOnPlane Function
6 statements
Source File
private function projectVecOnPlane(vecU, plane) result(res)
This function project given vector on an given plane
Example: projection of vector a onto a vector u is given as \f$ proj_u a = \frac{a \cdot u}{|u|^2} \cdot u \f$
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: vecU(3)
vector to project
type(tem_plane_type), intent(in) :: plane
plane on which vecU will be projected
Return Value real(kind=rk), (3)
output projected value
Called by
Call graph
sdr_find_periodic_neighbor calls projectveconplane
create_target calls sdr_find_periodic_neighbor
getbcid_and_calcqval calls sdr_find_periodic_neighbor
sdr_identify_boundary calls getbcid_and_calcqval
traverse_tree calls create_target, traverse_tree
proto2treelm calls sdr_identify_boundary
sdr_proto2treelm calls traverse_tree