proto2Treelm – Seeder
proto2Treelm Subroutine
78 statements
Source File
public subroutine proto2Treelm(node_pos, treeID, leVal, proto, geometry, check_bnd, temData, nodeprops, nodecolors, meshUniverse)
Routine to convert protoTree to Treelm data format. append all leaves to the temData%treeID
Add this element to the list of elements in the final tree, by adding: * treeID * propertyBits If there is a boundary, also add the correct boundary data into the 26 direct neighbors (bc_ID), append to all 26 even if there is no boundary condition in the given direction, no boundaries are indicated by 0, boundary conditions are decided based on the trumping rule, that is the minimal bc_ID of all boundary objects in the corresponding neighbor are chosen. Treat periodic boundaries here if possible by putting the opposite treeID into the bc_ID.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: node_pos
Position of leaf in the preliminary tree
integer(kind=long_k), intent(in) :: treeID
treeID of current node
type(levelValues_type), intent(in) :: leVal
level value of current node
type(sdr_protoTree_type), intent(in) :: proto
preliminary tree
type(sdr_geometry_type), intent(in) :: geometry
contains all geometrical objects
logical, intent(in) :: check_bnd
does this node has boundary neighbor
type(sdr_temData_type), intent(inout) :: temData
integer, intent(in) :: nodeprops
propertyBits of current node
character(len=1), intent(in) :: nodecolors(:)
Color information of the cuurent node
type(treelmesh_type), intent(inout) :: meshUniverse
contains bounding cube information
Calls
Called by
Call graph
proto2treelm calls append, sdr_identify_boundary, tem_CoordOfId, val
sdr_identify_boundary calls val, kindpos, getbcid_and_calcqval, getnormal, needcalcqvalbybcid, sdr_neighbor_in_proto, sdr_nodeprop_btest, tem_BaryOfId, tem_abort, tem_convertTreeIDtoCube, tem_pointCubeOverlap
getbcid_and_calcqval calls val, needcalcqvalbybcid, sdr_find_periodic_neighbor, sdr_qvalbynode, sdr_truncate_qval
getnormal calls append, val, kindpos, destroy, init, mrgrnk, tem_triangle_normal_proximity
needcalcqvalbybcid calls val, kindpos
sdr_neighbor_in_proto calls positionofval, tem_IdOfCoord, tem_ParentOf
sdr_find_periodic_neighbor calls tem_CoordOfId, val, kindpos, needcalcqvalbybcid, sdr_nodeprop_btest, tem_BaryOfId, tem_abort, sdr_qvalbynode, sdr_truncate_qval, tem_IdOfCoord, gettreeidposofcoord, projectveconplane, tem_CoordOfReal
sdr_qvalbynode calls val, fraction_PointLine, intersect_RayTriangle
sdr_truncate_qval calls sdr_nodeprop_btest
traverse_tree calls proto2treelm, traverse_tree
sdr_proto2treelm calls traverse_tree
seeder calls sdr_proto2treelm