sdr_load_canonicalND – Seeder
sdr_load_canonicalND Subroutine
30 statements
Source File
public subroutine sdr_load_canonicalND(pntArray, lineArray, triArray, boxArray, spaObjArray, attr_pos, transform, conf, thandle)
This routine loads canonical geometrial objects like point, line, plane and box and add them to the growing array of each primitive geometries and the position of this geometries are stored in the growing array of spatialObject
Arguments
Type Intent Optional Attributes Name
type(grw_pointarray_type), intent(inout) :: pntArray
growing array of points
type(grw_linearray_type), intent(inout) :: lineArray
growing array of line
type(grw_trianglearray_type), intent(inout) :: triArray
growing array of triangles
type(grw_boxarray_type), intent(inout) :: boxArray
growing array of boxes
type(grw_spatialObjArray_type), intent(inout) :: spaObjArray
growing array of geometrical objects.
integer, intent(in) :: attr_pos
Position of the attribute to connect this object to.
type(tem_transformation_type), intent(in) :: transform
transformation for spatial object
type(flu_State) :: conf
lua state
integer, intent(in) :: thandle
Calls
Called by
Call graph
sdr_load_canonicalnd calls append_canondboxtosdrbox, append_canondboxtotriangle, append_canondlinetosdrline, append_canondplanetotriangle, append_canondpointtosdrpoint, tem_load_canonicalND, upper_to_lower
append_canondboxtosdrbox calls append
append_canondboxtotriangle calls append_canondplanetotriangle
append_canondlinetosdrline calls append
append_canondplanetotriangle calls append
append_canondpointtosdrpoint calls append
sdr_load_geom_table_single calls sdr_load_canonicalnd
sdr_load_geom_table calls sdr_load_geom_table_single
sdr_load_spatialobject_single calls sdr_load_geom_table
sdr_load_geometry calls sdr_load_spatialobject_single