sdr_identify_boundary – Seeder
sdr_identify_boundary Subroutine
108 statements
Source File
public subroutine sdr_identify_boundary(node_pos, treeID, coord, leVal, proto, geometry, BC_ID, qVal, bc_normal, meshUniverse)
This routine checks for boundary neighbors and level of the boundary node
Note, this can not easily be used for target nodes with subelement resolution, as it assumes q-Values if the node is intersected by a boundary.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: node_pos
Position of leaf in the preliminary tree
integer(kind=long_k), intent(in) :: treeID
treeID of parent node
integer, intent(in) :: coord(4)
Coordinate of treeID
type(levelValues_type), intent(in) :: leVal
level value of parent node
type(sdr_protoTree_type), intent(in) :: proto
preliminary tree
type(sdr_geometry_type), intent(in) :: geometry
contains all geometrical objects
integer(kind=long_k), intent(out) :: BC_ID(qQQQ)
Boundary ID for all 26 neighbor directions
real(kind=rk), intent(out) :: qVal(qQQQ)
distance from boundary for all 26 neighbor directions
real(kind=rk), intent(out) :: bc_normal(3)
Wall normal pointing from the surface to the barycenter of the boundary element
type(treelmesh_type), intent(in) :: meshUniverse
contains bounding cube information
Calls
Called by
Call graph
sdr_identify_boundary calls kindpos, getbcid_and_calcqval, getnormal, needcalcqvalbybcid, sdr_neighbor_in_proto, sdr_nodeprop_btest, tem_BaryOfId, tem_abort, tem_convertTreeIDtoCube, tem_pointCubeOverlap, val
getbcid_and_calcqval calls needcalcqvalbybcid, val, sdr_find_periodic_neighbor, sdr_qvalbynode, sdr_truncate_qval
getnormal calls kindpos, val, append, destroy, init, mrgrnk, tem_triangle_normal_proximity
needcalcqvalbybcid calls kindpos, val
sdr_neighbor_in_proto calls positionofval, tem_IdOfCoord, tem_ParentOf
sdr_find_periodic_neighbor calls kindpos, needcalcqvalbybcid, sdr_nodeprop_btest, tem_BaryOfId, tem_abort, val, sdr_qvalbynode, sdr_truncate_qval, tem_IdOfCoord, gettreeidposofcoord, projectveconplane, tem_CoordOfId, tem_CoordOfReal
sdr_qvalbynode calls val, fraction_PointLine, intersect_RayTriangle
sdr_truncate_qval calls sdr_nodeprop_btest
gettreeidposofcoord calls sdr_nodeprop_btest, positionofval, tem_IdOfCoord, tem_CoordOfReal
proto2treelm calls sdr_identify_boundary
traverse_tree calls proto2treelm, traverse_tree
sdr_proto2treelm calls traverse_tree
seeder calls sdr_proto2treelm