sdr_dump_treelm – Seeder
sdr_dump_treelm Subroutine
250 statements
Source File
public subroutine sdr_dump_treelm(temData, geometry, confHeader)
This routine dumps the final fluid tree leaves in the disk
Arguments
Type Intent Optional Attributes Name
type(sdr_temData_type), intent(in) :: temData
temData contains final treelmesh
type(sdr_geometry_type), intent(in) :: geometry
Bounding cube, the prototree lives in.
type(sdr_confHead_type), intent(inout) :: confHeader
config header info.
Calls
Called by
Call graph
sdr_dump_treelm calls aot_out_close, aot_out_close_table, aot_out_open, aot_out_open_table, aot_out_val, append, destroy, dump_tem_global, newunit, ply_prj_header_out, tem_startTimer, tem_stopTimer, uni_name, val
ply_prj_header_out calls aot_out_val, ply_fpt_header_out, ply_fxt_header_out, ply_l2p_header_out
ply_fpt_header_out calls aot_out_val
ply_fxt_header_out calls aot_out_val
ply_l2p_header_out calls aot_out_val
seeder calls sdr_dump_treelm