sdr_hvs_props_load – Seeder
sdr_hvs_props_load Subroutine
50 statements
Source File
public subroutine sdr_hvs_props_load(me, varsys, mesh, proc)
Load the properties from the mesh.
Arguments
Type Intent Optional Attributes Name
type(sdr_hvs_props_type), intent(out) :: me
Properties to load.
type(tem_varSys_type), intent(inout) :: varsys
A variable system, to which the colors should be appended.
type(treelmesh_type), intent(in) :: mesh
Mesh to load the properties for.
type(tem_comm_env_type), intent(in) :: proc
Process description for MPI-IO
Calls
Called by
Call graph
sdr_hvs_props_load calls color_label, init_tem_bc_prop, ply_subresolution_load, sdr_hvs_props_clean, tem_color_prop_load, tem_varSys_append_derVar
ply_subresolution_load calls aot_get_val, close_config, tem_abort, tem_open_distconf, tem_subres_prop_load, upper_to_lower
sdr_hvs_config_load calls sdr_hvs_props_load
sdr_harvesting calls sdr_hvs_config_load