sdr_load_transformation – Seeder
sdr_load_transformation Subroutine
15 statements
Source File
public subroutine sdr_load_transformation(transform, conf, thandle)
This routine loads the transformation table for each spatial object table in config file
If single spatial object contains multiple geometry then the transformation is applied to all geometries defined in that spatial object
Arguments
Type Intent Optional Attributes Name
type(sdr_transformation_type), intent(out) :: transform
transformation for spatial object
type(flu_State) :: conf
lua state
integer, intent(in) :: thandle
spatial object parent handle
Calls
Call graph
sdr_load_transformation calls aot_table_close, aot_table_open, sdr_load_deformation, sdr_load_translation
sdr_load_deformation calls aot_table_close, aot_table_open, aot_get_val, tem_abort
sdr_load_translation calls aot_table_close, aot_table_open, aot_get_val, tem_abort