sdr_load_deformation – Seeder
sdr_load_deformation Subroutine
55 statements
Source File
private subroutine sdr_load_deformation(deform, conf, thandle)
This routine loads the deformation table from transformation table
Arguments
Type Intent Optional Attributes Name
type(sdr_deformation_type), intent(out) :: deform
deform for spatial object
type(flu_State) :: conf
lua state
integer, intent(in) :: thandle
spatial object parent handle
Calls
Called by
Call graph
sdr_load_deformation calls aot_get_val, aot_table_close, aot_table_open, tem_abort
sdr_load_transformation calls sdr_load_deformation