sdr_find_periodic_neighbor – Seeder
sdr_find_periodic_neighbor Subroutine
111 statements
Source File
public subroutine sdr_find_periodic_neighbor(elemBary, iDir, bc_ID, qVal, unKnownBnd, neighbor_pos, neighbor_level, leVal, proto, geometry, meshUniverse)
This routine find the treeID on the opposite side neighbor of the periodic plane for current leaf node
write(dbgUnit(5),*) '1.1 qVal ', qVal
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: elemBary(3)
current element barycenter
integer, intent(in) :: iDir
Current boundary neighbor direction
integer(kind=long_k), intent(inout) :: bc_ID
treeiD of opposite neighbor with periodic plane
real(kind=rk), intent(out) :: qVal
distance from boundary for direction iDir
Todo
HK: maybe turn this optional, why is it relevant for periodic?
logical, intent(inout) :: unKnownBnd
Set to true if a neighbor with no property is encountered
integer, intent(in) :: neighbor_pos
position of neighbor treeID in the proto%node list
integer, intent(in) :: neighbor_level
level of the periodic boundary neighbor node
type(levelValues_type), intent(in) :: leVal
level value of parent node
type(sdr_protoTree_type), intent(in) :: proto
preliminary tree
type(sdr_geometry_type), intent(in) :: geometry
contains all geometrical objects
type(treelmesh_type), intent(in) :: meshUniverse
contains bounding cube information
Calls
Called by
Call graph
sdr_find_periodic_neighbor calls kindpos, gettreeidposofcoord, needcalcqvalbybcid, projectveconplane, sdr_qvalbynode, sdr_truncate_qval, sdr_nodeprop_btest, tem_BaryOfId, tem_CoordOfId, tem_CoordOfReal, tem_IdOfCoord, tem_abort, val
gettreeidposofcoord calls sdr_nodeprop_btest, tem_CoordOfReal, tem_IdOfCoord, positionofval
needcalcqvalbybcid calls kindpos, val
sdr_qvalbynode calls val, fraction_PointLine, intersect_RayTriangle
sdr_truncate_qval calls sdr_nodeprop_btest
create_target calls sdr_find_periodic_neighbor
getbcid_and_calcqval calls sdr_find_periodic_neighbor
sdr_identify_boundary calls getbcid_and_calcqval
traverse_tree calls create_target, traverse_tree, proto2treelm
proto2treelm calls sdr_identify_boundary
sdr_proto2treelm calls traverse_tree
seeder calls sdr_proto2treelm