sdr_write_proto_as_restart – Seeder
sdr_write_proto_as_restart Subroutine
86 statements
Source File
public subroutine sdr_write_proto_as_restart(proto, geometry, itime, header, prefix)
Write current leaves of the prototree as treelm restart.
This routine is mainly for debugging, to allow the visualization of the tree with harvester. The mesh will not contain any properties, instead additional data is provided as restart. Note that recursive output is used, to write each leaf node on its own, this output is thus really only useful for debugging, and might take very long for large meshes, however memory consumption should be fairly small.
Todo
SDR_write_proto_as_restart is a explicitly serial routine, deploying its own writing to save memory. Therefore this is some code duplication from treelmesh_module::dump_treelmesh.
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(in) :: proto
The prototree to output.
type(sdr_geometry_type), intent(in) :: geometry
Bounding cube, the prototree lives in.
integer, intent(in) :: itime
wave number in character format to prepend to filenames and timestamp
type(sdr_confHead_type), intent(in) :: header
some global information on solver name and version
character(len=*), intent(in), optional :: prefix
prefix for filenames
Calls
Called by
Call graph
sdr_write_proto_as_restart calls dump_tem_global, newunit, protodata_ofnode, write_childleaves, sdr_append_protovar, sdr_nodeprop_btest, tem_create_varMap, tem_restart_writeHeader, tem_solverTag, tem_varSys_init, val
protodata_ofnode calls sdr_nodeprop_btest, val
write_childleaves calls protodata_ofnode, write_childleaves, sdr_nodeprop_btest, val
floodwaves_tree calls sdr_write_proto_as_restart
seeder calls sdr_write_proto_as_restart, sdr_flood_tree
sdr_flood_tree calls floodwaves_tree