sdr_append_distanceRefineObject – Seeder
sdr_append_distanceRefineObject Subroutine
49 statements
Source File
public subroutine sdr_append_distanceRefineObject(coord, dx, iLevel, geometry, intersected_first, intersected_last, intersected_object)
This routine created sphere objects and new attribute and extend a list of spatial objects if node intersected boundary has distance refine.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: coord(4)
Coordinate of current node
real(kind=rk), intent(in) :: dx
integer, intent(in) :: iLevel
Current node level
type(sdr_geometry_type), intent(inout) :: geometry
type which contains all geometry object infos
integer, intent(in) :: intersected_first
This node's first position in intersected_object
integer, intent(in) :: intersected_last
This node's last position in intersected_object
type(grw_intarray_type), intent(in) :: intersected_object
Growing array of intersected_objects
Calls
Called by
Call graph
sdr_append_distancerefineobject calls append, kindpos, uni_name
sdr_build_prototree calls sdr_append_distancerefineobject
seeder calls sdr_build_prototree