sdr_qValByNode – Seeder
sdr_qValByNode Subroutine
42 statements
Source File
public subroutine sdr_qValByNode(proto, geometry, dx, iDir, origin, node_pos, qVal)
This routine computes the minimum distance of a given link and all the geometries in a given node:\n the link is given by a vector and a origin point.\n the node is given by the node position in the protoTree.\n If there is no intersection, qVal returns -1.0
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(in) :: proto
preliminary tree
type(sdr_geometry_type), intent(in) :: geometry
contains all geometrical objects
real(kind=rk), intent(in) :: dx
dx of current level
integer, intent(in) :: iDir
Direction
real(kind=rk), intent(in) :: origin(3)
current element barycenter
integer :: node_pos
position of node to find the geometries
real(kind=rk), intent(out) :: qVal
distance from boundary for all 26 neighbor directions
Calls
Called by
Call graph
sdr_qvalbynode calls fraction_PointLine, intersect_RayTriangle, val
flood_periphery calls sdr_qvalbynode
getbcid_and_calcqval calls sdr_qvalbynode, sdr_find_periodic_neighbor
sdr_find_periodic_neighbor calls sdr_qvalbynode
create_target calls sdr_find_periodic_neighbor
sdr_flood_tree calls flood_periphery
sdr_identify_boundary calls getbcid_and_calcqval
proto2treelm calls sdr_identify_boundary
traverse_tree calls create_target, proto2treelm, traverse_tree
seeder calls sdr_flood_tree
sdr_proto2treelm calls traverse_tree