sdr_load_config – Seeder
sdr_load_config Subroutine
39 statements
Source File
public subroutine sdr_load_config(me, geometry)
Load the configuration from the Lua script provided on the command line or from seeder.lua by default, if no file name is given as program argument.
The configuration needs to describe some general properties, like the directory where the resulting mesh is to be stored and the geometries, that are to be used to define the mesh.
Arguments
Type Intent Optional Attributes Name
type(sdr_confHead_type), intent(inout) :: me
contains basic information from config file
type(sdr_geometry_type), intent(out) :: geometry
contains all geometry object defined in the config file
Calls
Called by
Call graph
sdr_load_config calls aot_get_val, close_config, open_config_file, sdr_load_geometry, sdr_load_inverted, sdr_subresolution_encolor, sdr_subresolution_load, tem_abort, tem_debug_load_main, tem_load_general, tem_logging_load_primary, tem_startTimer, tem_stopTimer, uni_name
seeder calls sdr_load_config