sdr_neighbor_in_proto – Seeder
sdr_neighbor_in_proto Function
25 statements
Source File
public function sdr_neighbor_in_proto(proto, coord, iDir, neighbor_level) result(pos)
Find the neighbor position in protoTree for iDir on the same level or on any one above.
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(in) :: proto
preliminary tree
integer, intent(in) :: coord(4)
integer, intent(in) :: iDir
integer, intent(out) :: neighbor_level
Return Value integer
Calls
Called by
Call graph
sdr_neighbor_in_proto calls positionofval, tem_IdOfCoord, tem_ParentOf
check_bndlevel calls sdr_neighbor_in_proto
create_target calls sdr_neighbor_in_proto
flood_periphery_diagonal calls sdr_neighbor_in_proto
sdr_identify_boundary calls sdr_neighbor_in_proto
sdr_mark_neighborhasbnd calls sdr_neighbor_in_proto
flood_periphery calls flood_periphery_diagonal
proto2treelm calls sdr_identify_boundary
sdr_build_prototree calls sdr_mark_neighborhasbnd
sdr_refine_leaf calls check_bndlevel
traverse_tree calls create_target, proto2treelm, traverse_tree
sdr_flood_tree calls flood_periphery
sdr_proto2treelm calls traverse_tree
seeder calls sdr_build_prototree, sdr_refine_leaf, sdr_flood_tree, sdr_proto2treelm