sdr_build_protoTree – Seeder
sdr_build_protoTree Subroutine
138 statements
Source File
public subroutine sdr_build_protoTree(me, geometry, header)
This routine builds the preliminary tree with geometry intersection and neighbor identification
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(out) :: me
preliminary tree created by this routine
type(sdr_geometry_type), intent(inout) :: geometry
type which contains all geometry object infos
type(sdr_confHead_type), intent(inout) :: header
some global information on solver name and version
Calls
Called by
Call graph
sdr_build_prototree calls append, init, create_children, sdr_append_distancerefineobject, sdr_mark_neighborhasbnd, sdr_node_neighbors, sdr_any_bc_distancerefine, sdr_any_bc_subresolution, sdr_clear_nodeprop_bit, sdr_mark_floodnode, sdr_nodeprop_btest, sdr_set_nodeprop_bit, sdr_wetneighborsface, tem_CoordOfId, tem_FirstIdAtLevel, tem_abort, tem_horizontalSpacer, tem_startTimer, tem_stopTimer, truncate, uni_name, val
seeder calls sdr_build_prototree