sdr_proto2treelm – Seeder
sdr_proto2treelm Subroutine
58 statements
Source File
public subroutine sdr_proto2treelm(proto, geometry, temData, header)
This subroutine creates the treelmesh from the flooded prototree.
It will create the treelmesh out of all flooded elements and refine those leaves intersected by a refinement object. This routine will also identify the elements with boundary conditions and store the boundary information accordingly. Please keep in mind, that the flooding only considered the 6 face neighbors, while we create boundary informations for all 26 neighbors.
Todo
Neighbors that do not intersect boundary objects. This means, that it might happen, that any of the 20 further neighbors does not actually intersect a boundary object. We need to deal with this case properly. For example, a boundary condition might be selected based on the adjacent face neighbors for the direction in question.
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(inout) :: proto
preliminary tree
type(sdr_geometry_type), intent(in) :: geometry
contains all geometrical objects
type(sdr_temData_type), intent(inout) :: temData
temData contains final mesh created by this routine
type(sdr_confHead_type), intent(inout) :: header
Header data.
Calls
Called by
Call graph
sdr_proto2treelm calls init, ply_poly_project_fillbody, traverse_tree, tem_FirstIdAtLevel, tem_startTimer, tem_stopTimer
traverse_tree calls traverse_tree, tem_FirstIdAtLevel, create_target, proto2treelm, sdr_nodecolors, val
create_target calls val, append, bc_color_id, newunit, ply_convertfromoversample, ply_poly_project_n2m, positionofval, sdr_color_points, sdr_find_periodic_neighbor, sdr_neighbor_in_proto, sdr_bitfieldcolors, sdr_color_log2char, sdr_nodeprop_btest, tem_CoordOfId, tem_abort
proto2treelm calls val, append, sdr_identify_boundary, tem_CoordOfId
seeder calls sdr_proto2treelm