sdr_hvs_config_load – Seeder
sdr_hvs_config_load Subroutine
45 statements
Source File
public subroutine sdr_hvs_config_load(me, mesh, property, varsys, general, restart, time)
Read the configuration for the Seeder harvesting from a Lua script.
Arguments
Type Intent Optional Attributes Name
type(sdr_hvs_config_type), intent(out) :: me
Seeder harvesting configuration to load
type(treelmesh_type), intent(out) :: mesh
Treelm mesh description as obtained from the user configuration.
type(sdr_hvs_props_type), intent(out) :: property
Properties associated with the mesh.
type(tem_varSys_type), intent(inout) :: varsys
A variable system, to which the further variables should be appended.
type(tem_general_type), intent(inout) :: general
General treelm data to load
type(tem_restart_type), intent(inout) :: restart
type(tem_time_type), intent(out) :: time
Calls
Called by
Call graph
sdr_hvs_config_load calls aot_get_val, close_config, hvs_output_load, load_tem, open_config_file, ply_sampled_tracking_load, sdr_hvs_props_load, tem_debug_load_main, tem_load_general, tem_load_restart, tem_logging_load_primary
ply_sampled_tracking_load calls ply_sampling_load, tem_load_tracking
sdr_hvs_props_load calls color_label, init_tem_bc_prop, ply_subresolution_load, sdr_hvs_props_clean, tem_color_prop_load, tem_varSys_append_derVar
ply_subresolution_load calls aot_get_val, close_config, tem_abort, tem_open_distconf, tem_subres_prop_load, upper_to_lower
sdr_harvesting calls sdr_hvs_config_load