sdr_subresolution_load – Seeder
sdr_subresolution_load Subroutine
69 statements
Source File
public subroutine sdr_subresolution_load(subres, conf, parent)
Loading the settings for the subresolution in the mesh.
Arguments
Type Intent Optional Attributes Name
type(sdr_subresolution_type), intent(out) :: subres
The subresolution data structure to fill.
type(flu_State) :: conf
Handle to the Lua configuration script.
integer, intent(in), optional :: parent
Handle to a possible parent table.
Calls
Called by
Call graph
sdr_subresolution_load calls aot_get_val, aot_table_close, aot_table_open, ply_prj_init_define, ply_prj_header_load, sdr_subres_fills_load, subres_load_color_defaults, tem_abort, upper_to_lower
ply_prj_header_load calls aot_get_val, tem_abort, upper_to_lower, ply_fpt_header_display, ply_fpt_header_load, ply_fxt_header_display, ply_fxt_header_load, ply_l2p_header_display, ply_l2p_header_load
sdr_subres_fills_load calls aot_table_open, aot_table_length, init, load_single_fill
subres_load_color_defaults calls aot_get_val, aot_table_close, aot_table_open, tem_abort, upper_to_lower, aot_table_length, append, init
load_single_fill calls aot_get_val, aot_table_close, aot_table_open, tem_abort, sdr_subres_fills_add
ply_fpt_header_load calls aot_get_val, tem_abort, upper_to_lower
ply_fxt_header_load calls aot_get_val, tem_abort
ply_l2p_header_load calls aot_get_val, tem_abort, upper_to_lower
sdr_subres_fills_add calls upper_to_lower, append
sdr_load_config calls sdr_subresolution_load
seeder calls sdr_load_config