sdr_truncate_qVal – Seeder
sdr_truncate_qVal Subroutine
19 statements
Source File
private subroutine sdr_truncate_qVal(proto, qVal, BCID, neighPos, treeID_periodic)
This routine gives special treatment when qVal > 1.0 or qVal == -1.0 for flooded neighbor, treat it as normal fluid: clean BCID, set qVal to -1 (no itersection). for non-flooded neighbor, treat it as high order wall: set qVal to 1
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(in) :: proto
preliminary tree
real(kind=rk), intent(inout) :: qVal
qValue
integer(kind=long_k), intent(inout) :: BCID
boundary id
integer, intent(in) :: neighPos
neighbor position in proto tree
integer(kind=long_k), intent(in), optional :: treeID_periodic
negative treeID of periodic domain
Calls
Called by
Call graph
sdr_truncate_qval calls sdr_nodeprop_btest
getbcid_and_calcqval calls sdr_truncate_qval, sdr_find_periodic_neighbor
sdr_find_periodic_neighbor calls sdr_truncate_qval
create_target calls sdr_find_periodic_neighbor
sdr_identify_boundary calls getbcid_and_calcqval
proto2treelm calls sdr_identify_boundary
traverse_tree calls create_target, proto2treelm, traverse_tree
sdr_proto2treelm calls traverse_tree