sdr_inHerit_distanceRefineObject – Seeder
sdr_inHerit_distanceRefineObject Subroutine
57 statements
Source File
public subroutine sdr_inHerit_distanceRefineObject(proto, geometry)
This routines inherit distance refine sphere object from root node down to leaf node. Only the object with level greater than node level are inHerited
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(inout) :: proto
The proto tree description with all the data to refine further
type(sdr_geometry_type), intent(in) :: geometry
type which contains all geometry object infos
Calls
Called by
Call graph
sdr_inherit_distancerefineobject calls inherit_intersectedobject, tem_FirstIdAtLevel, tem_horizontalSpacer, tem_startTimer, tem_stopTimer, val
inherit_intersectedobject calls val, append, is_intersecting, sdr_append_childintersectedobject, tem_CoordOfId, tem_sphereCubeOverlap
is_intersecting calls val, tem_sphereCubeOverlap, sdr_periodicplanecubeoverlap, sdr_spacerinterwovencubeoverlap, tem_boxCubeOverlap, tem_cylinderCubeOverlap, tem_ellipsoidCubeOverlap, tem_lineCubeOverlap, tem_pointCubeOverlap, tem_triangleCubeOverlap
seeder calls sdr_inherit_distancerefineobject