sdr_flood_tree – Seeder
sdr_flood_tree Subroutine
15 statements
Source File
public subroutine sdr_flood_tree(proto, geometry, header, meshUniverse)
This routine identifies the nodes, which are supposed to be part of the computational domain, as defined by the seed objects.
Mark all virtual nodes, which contain a flooded child as flooded starting from the second finest level moving up to the root. This allows to easily avoid non-flooded domains later on.
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(inout) :: proto
The proto tree description with all the data enabling the flooding.
type(sdr_geometry_type), intent(in) :: geometry
Description of geometric objects. Propably not needed here, remove again if this is the case.
type(sdr_confHead_type), intent(inout) :: header
some global information on solver name and version
type(treelmesh_type), intent(in) :: meshUniverse
treelmesh contains bounding cube info
Calls
Called by
Call graph
sdr_flood_tree calls flood_parents, flood_periphery, floodwaves_tree, tem_log, tem_startTimer, tem_stopTimer, tem_toStr, val
flood_parents calls val
flood_periphery calls tem_log, tem_toStr, val, flood_periphery_diagonal, needcalcqvalbybcid, needflddglbybcid, sdr_qvalbynode, sdr_mark_floodnode, tem_BaryOfId, tem_ElemSize
floodwaves_tree calls tem_log, tem_toStr, val, sdr_write_proto_as_restart, sdr_mark_floodnode, sdr_wetneighborsface, tem_directChildren, tem_eligibleChildren
seeder calls sdr_flood_tree