sdr_hvs_props_import_dofs – Seeder
sdr_hvs_props_import_dofs Subroutine
15 statements
Source File
public subroutine sdr_hvs_props_import_dofs(me, mesh, proc, maxdegree, ndims)
Import subresolved color data.
Arguments
Type Intent Optional Attributes Name
type(sdr_hvs_props_type), intent(inout) :: me
Properties to get the subresolution dofs for.
type(treelmesh_type), intent(in) :: mesh
Mesh definition, these properties belong to.
type(tem_comm_env_type), intent(in) :: proc
Communicating environment.
integer, intent(in) :: maxdegree
Maximal polynomial degree to import.
Set to 0, if only the integral mean value is to be loaded.
integer, intent(in) :: ndims
Dimensions of the polynomials after importing.
Calls
Called by
Call graph
sdr_hvs_props_import_dofs calls ply_subres_import_color
ply_subres_import_color calls nelems, newunit, offset, ply_transfer_dofs, ply_transfer_p_dim, tem_abort
sdr_harvesting calls sdr_hvs_props_import_dofs