sdr_load_spatialObject_single – Seeder
sdr_load_spatialObject_single Subroutine
12 statements
Source File
public subroutine sdr_load_spatialObject_single(me, subres_colors, conf, thandle)
Routine to load single spatial object table defined in config file
Arguments
Type Intent Optional Attributes Name
type(sdr_geometry_type), intent(inout) :: me
contains all geometry infomation
type(dyn_labelarray_type), intent(in) :: subres_colors
All the colors, which should be default use subelement resolution for their boundaries.
type(flu_State) :: conf
integer, intent(in) :: thandle
Calls
Called by
Call graph
sdr_load_spatialobject_single calls sdr_load_geom_table, sdr_load_attribute, tem_horizontalSpacer, tem_load_transformation
sdr_load_geom_table calls aot_table_close, aot_table_length, aot_table_open, sdr_load_geom_table_single, tem_abort
sdr_load_geom_table_single calls tem_abort, aot_get_val, sdr_load_canonicalnd, sdr_load_cylinder, sdr_load_ellipsoid, sdr_load_sphere, sdr_load_stl, sdr_load_triangle, sdr_load_periodic, sdr_load_spacer, upper_to_lower
sdr_load_geometry calls sdr_load_spatialobject_single
sdr_load_config calls sdr_load_geometry
seeder calls sdr_load_config