sdr_load_geometry – Seeder
sdr_load_geometry Subroutine
94 statements
Source File
public subroutine sdr_load_geometry(me, subres_colors, invert_colors, conf)
Routine to load spatial object defined in config file and store in geometry type
Arguments
Type Intent Optional Attributes Name
type(sdr_geometry_type), intent(out) :: me
contains all geometry infomation
type(dyn_labelarray_type), intent(in) :: subres_colors
All the colors, which should be default use subelement resolution for their boundaries.
type(dyn_labelarray_type), intent(in) :: invert_colors
type(flu_State) :: conf
Calls
Called by
Call graph
sdr_load_geometry calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, color_inverted, init, kindpos, sdr_load_spatialobject_single, sdr_identify_bc_colors, sdr_identify_inv_colors, sdr_init_attribute, tem_load_cube, truncate, uni_name, val
sdr_load_spatialobject_single calls sdr_load_geom_table, sdr_load_attribute, tem_horizontalSpacer, tem_load_transformation
sdr_load_geom_table calls aot_table_close, aot_table_length, aot_table_open, sdr_load_geom_table_single, tem_abort
sdr_load_geom_table_single calls aot_get_val, tem_abort, sdr_load_canonicalnd, sdr_load_cylinder, sdr_load_ellipsoid, sdr_load_sphere, sdr_load_stl, sdr_load_triangle, sdr_load_periodic, sdr_load_spacer, upper_to_lower
sdr_load_config calls sdr_load_geometry
seeder calls sdr_load_config