sdr_load_geom_table – Seeder
sdr_load_geom_table Subroutine
31 statements
Source File
public subroutine sdr_load_geom_table(me, conf, thandle, attr_pos, transform)
This routine loads the geometry table from the config file i.e loading different geometry kinds like canoND, cube, periodic, STL etc.
Arguments
Type Intent Optional Attributes Name
type(sdr_geometry_type), intent(inout) :: me
type(flu_State) :: conf
integer, intent(in) :: thandle
integer, intent(in) :: attr_pos
Position of the attribute to connect the geometric objects to.
type(tem_transformation_type), intent(in) :: transform
Calls
Called by
Call graph
sdr_load_geom_table calls aot_table_close, aot_table_length, aot_table_open, sdr_load_geom_table_single, tem_abort
sdr_load_geom_table_single calls tem_abort, aot_get_val, sdr_load_canonicalnd, sdr_load_cylinder, sdr_load_ellipsoid, sdr_load_sphere, sdr_load_stl, sdr_load_triangle, sdr_load_periodic, sdr_load_spacer, upper_to_lower
sdr_load_canonicalnd calls upper_to_lower, append_canondboxtosdrbox, append_canondboxtotriangle, append_canondlinetosdrline, append_canondplanetotriangle, append_canondpointtosdrpoint, tem_load_canonicalND
sdr_load_cylinder calls append_cylinder2spaobj, tem_load_cylinder
sdr_load_ellipsoid calls append, tem_load_ellipsoid
sdr_load_sphere calls append, tem_load_sphere
sdr_load_stl calls append, tem_load_stl
sdr_load_triangle calls append, tem_load_triangle
append_canondboxtosdrbox calls append
append_canondboxtotriangle calls append_canondplanetotriangle
append_canondlinetosdrline calls append
append_canondplanetotriangle calls append
append_canondpointtosdrpoint calls append
append_cylinder2spaobj calls append
sdr_load_spatialobject_single calls sdr_load_geom_table
sdr_load_geometry calls sdr_load_spatialobject_single
sdr_load_config calls sdr_load_geometry
seeder calls sdr_load_config