sdr_refine_leaf – Seeder
sdr_refine_leaf Subroutine
124 statements
Source File
public subroutine sdr_refine_leaf(proto, geometry)
This routine extends the protoTree with max of minlevel or level of refinement object.
If it is a leaf, check for intersected objects, and keep on refining accordingly down to the maximum requested level. When the desired level is reached (no refinement object, or desired level of intersected refinement object reached, check all (26) direct neigbors. If there is a neighbor intersected by a boundary check its refinement level, if it is higher then the current one, do another refinement step.
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(inout) :: proto
The proto tree description with all the data to refine further
type(sdr_geometry_type), intent(in) :: geometry
type which contains all geometry object infos
Calls
Called by
Call graph
sdr_refine_leaf calls append, destroy, init, check_bndlevel, create_children, inherit_intersectedobject, sdr_set_nodeprop_bit, sorted, tem_FirstIdAtLevel, tem_horizontalSpacer, tem_startTimer, tem_stopTimer, truncate, val
check_bndlevel calls val, sdr_neighbor_in_proto, sdr_nodeprop_btest, tem_CoordOfId
create_children calls append, sdr_set_nodeprop_bit, val, sdr_clear_nodeprop_bit, sdr_inheritbnd_eligiblechildren, tem_directChildren
inherit_intersectedobject calls append, val, is_intersecting, sdr_append_childintersectedobject, tem_CoordOfId, tem_sphereCubeOverlap
seeder calls sdr_refine_leaf