sdr_mark_neighborHasBnd – Seeder
sdr_mark_neighborHasBnd Subroutine
12 statements
Source File
private subroutine sdr_mark_neighborHasBnd(proto, coord)
This routine marks 26 direct neighbors as has boundary bit
Arguments
Type Intent Optional Attributes Name
type(sdr_protoTree_type), intent(inout) :: proto
neighbors are identified for this tree and neighbors as marked with hasBoundary_bit
integer, intent(in) :: coord(4)
Coordinate of current node
Calls
Called by
Call graph
sdr_mark_neighborhasbnd calls sdr_neighbor_in_proto, sdr_set_nodeprop_bit, val
sdr_neighbor_in_proto calls positionofval, tem_IdOfCoord, tem_ParentOf
sdr_build_prototree calls sdr_mark_neighborhasbnd
seeder calls sdr_build_prototree