sdr_subres_fills_load – Seeder
sdr_subres_fills_load Subroutine
18 statements
Source File
public subroutine sdr_subres_fills_load(fills, conf, parent)
Load the filling definition for subresolved colors.
A filling is defined by a value for the area where the domain is flooded by the color specified in the label and a value for the remaining part of the domain without flooding.
The filling information has to be provided as a list of tables in the following form within the subresolution definition: \code{.lua} values = { { label = 'colA', fill = 1.0, void = 0.0 }, { label = 'colB', fill = 9.0, void = 0.1 } } \endcode Defaults are: fill=1.0, void=0.0.
Arguments
Type Intent Optional Attributes Name
type(sdr_subres_fills_type), intent(out) :: fills
Value definitions for individual colors.
type(flu_State) :: conf
Handle for the Lua script.
integer, intent(in) :: parent
Parent table, within which to open the fills table.
Calls
Called by
Call graph
sdr_subres_fills_load calls aot_table_length, aot_table_open, init, load_single_fill
load_single_fill calls aot_table_open, aot_get_val, aot_table_close, sdr_subres_fills_add, tem_abort
sdr_subres_fills_add calls append, upper_to_lower
sdr_subresolution_load calls sdr_subres_fills_load
sdr_load_config calls sdr_subresolution_load
seeder calls sdr_load_config