sdr_dumptimers – Seeder
sdr_dumptimers Subroutine
39 statements
Source File
public subroutine sdr_dumptimers(general, nFluids, nBnds)
Performance results are written to a file for statistical review
write file
Arguments
Type Intent Optional Attributes Name
type(tem_general_type), intent(in) :: general
Parameters of the current simulation
integer, intent(in) :: nFluids
Number of fluid elements in dumped mesh
integer, intent(in) :: nBnds
Number of fluid elements which has boundary in dumped mesh
Calls
Called by
Call graph
sdr_dumptimers calls newunit, tem_getMaxTimerVal, tem_getTimerName
seeder calls sdr_dumptimers