sdr_subresolution_encolor – Seeder
sdr_subresolution_encolor Subroutine
21 statements
Source File
public subroutine sdr_subresolution_encolor(me, colors)
Find the value definitions for all unique colors.
Arguments
Type Intent Optional Attributes Name
type(sdr_subresolution_type), intent(inout) :: me
type(dyn_labelarray_type), intent(in) :: colors
Calls
Called by
Call graph
sdr_subresolution_encolor calls sdr_subres_fills_add
sdr_subres_fills_add calls append, upper_to_lower
sdr_load_config calls sdr_subresolution_encolor
seeder calls sdr_load_config