sdr_load_inverted – Seeder
sdr_load_inverted Subroutine
25 statements
Source File
private subroutine sdr_load_inverted(invlist, conf)
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type), intent(out) :: invlist
List of labels for inverted colors.
type(flu_State) :: conf
Lua script handle to read the inversion list from.
Calls
Called by
Call graph
sdr_load_inverted calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, append, init, tem_abort, upper_to_lower
sdr_load_config calls sdr_load_inverted
seeder calls sdr_load_config