sdr_subres_fills_add – Seeder
sdr_subres_fills_add Subroutine
13 statements
Source File
public subroutine sdr_subres_fills_add(fills, colorname, fill_value, void_value, pos, wasAdded)
Add a value definition for a color to the list of fillings.
Arguments
Type Intent Optional Attributes Name
type(sdr_subres_fills_type), intent(inout) :: fills
Table of color values to add a color definition to.
character(len=*), intent(in) :: colorname
Name of the color to define values for.
real(kind=rk), intent(in) :: fill_value
Value to use, where the domain is flooded by color.
real(kind=rk), intent(in) :: void_value
Value to use, where the domain is NOT flooded by color.
integer, intent(out) :: pos
Position of this color in the list of color values.
logical, intent(out) :: wasAdded
Indicator, if this value definition was added to the list.
Calls
Called by
Call graph
sdr_subres_fills_add calls append, upper_to_lower
load_single_fill calls sdr_subres_fills_add
sdr_subresolution_encolor calls sdr_subres_fills_add
sdr_load_config calls sdr_subresolution_encolor, sdr_subresolution_load
sdr_subres_fills_load calls load_single_fill
sdr_subresolution_load calls sdr_subres_fills_load
seeder calls sdr_load_config