transformCanoND_single – Seeder
transformCanoND_single Subroutine
16 statements
Source File
private subroutine transformCanoND_single(canoND, transform)
This routine apply transformation to canonical objects.
Arguments
Type Intent Optional Attributes Name
type(tem_canonicalND_type), intent(inout) :: canoND
canonical geometry object type
type(sdr_transformation_type), intent(in) :: transform
transformation for spatial object
Called by
Call graph
sdr_transformcanond calls transformcanond_single, transformcanond
transformcanond calls transformcanond_single