write_childLeaves – Seeder
write_childLeaves Subroutine
24 statements
Source File
private recursive subroutine write_childLeaves(meshunit, restunit, iLeaf, node_pos, proto, geometry, level)
Small helping routine to write leaves in order into a treelmesh formatted file.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: meshunit
integer, intent(in) :: restunit
integer, intent(inout) :: iLeaf
integer, intent(in) :: node_pos
type(sdr_protoTree_type), intent(in) :: proto
type(sdr_geometry_type), intent(in) :: geometry
integer, intent(in) :: level
Calls
Called by
Call graph
write_childleaves calls write_childleaves, protodata_ofnode, sdr_nodeprop_btest, val
protodata_ofnode calls sdr_nodeprop_btest, val
sdr_write_proto_as_restart calls write_childleaves
floodwaves_tree calls sdr_write_proto_as_restart
seeder calls sdr_write_proto_as_restart, sdr_flood_tree
sdr_flood_tree calls floodwaves_tree