sdr_harvesting – Seeder
sdr_harvesting Program
90 statements
Source File
Uses
iso_c_binding
hvs_output_module
tem_varMap_module
sdr_hvs_config_module
ply_dof_module
env_module
sdr_protoData_module
tem_bc_prop_module
tem_logging_module
tem_time_module
treelmesh_module
tem_restart_module
tem_general_module
tem_varSys_module
tem_color_prop_module
sdr_hvs_props_module
tem_tracking_module
tem_stencil_module
tem_meshInfo_module
ply_sampled_tracking_module
Seeder Harvesting Tool Visualization of meshes, generated by seeder. (c) 2015 University of Siegen
For a documentation, run ./waf gendoxy and find the documentation at ./Documentation/html/index.html
Todo
HK: no subsampling if we dump all data (no tracking)? Probably should do subsampling also here?
Calls
Variables
Type Attributes Name Initial
type(tem_restart_type) :: restart
type(sdr_protoData_type), target :: protoData
type(tem_general_type) :: general
type(treelmesh_type) :: mesh
type(sdr_hvs_config_type) :: config
type(sdr_hvs_props_type) :: property
type(hvs_output_file_type) :: out_file
type(tem_varSys_type) :: varsys
type(tem_varMap_type) :: varMap
type(tem_stencilHeader_type) :: stencil
type(tem_time_type) :: time
procedure(tem_varSys_proc_element), pointer :: get_element
integer :: iTrack
integer :: nDofs
integer :: nSimpleVars
integer, allocatable :: var_degree(:)
integer, allocatable :: lvl_degree(:)
integer, allocatable :: var_space(:)
character(len=pathLen) :: basename
Call graph
sdr_harvesting calls hvs_output_close, hvs_output_finalize, hvs_output_init, hvs_output_open, hvs_output_write, instance, ply_sampled_track_init, ply_sampled_track_output, sdr_hvs_config_load, sdr_hvs_props_import_dofs, sdr_append_protovar, sdr_readrestart, tem_create_stencil, tem_create_varMap, tem_finalize, tem_init_restart, tem_start, tem_time_reset, tem_varSys_append_meshInfoVar, tem_varSys_init, val