seeder – Seeder
seeder Program
42 statements
Source File
Uses
sdr_timer_module
sdr_proto2treelm_module
sdr_protoTree_module
sdr_flooding_module
sdr_refinePT_module
tem_timer_module
tem_debug_module
sdr_geometry_module
sdr_config_module
sdr_aux_module
tem_general_module
S E E D E R Mesh generator within the APES suite
For a documentation, run ./waf gendoxy and find the documentation at ./Documentation/html/index.html
Calls
Variables
Type Attributes Name Initial
type(sdr_confHead_type) :: header
type(sdr_geometry_type) :: geometry
type(sdr_protoTree_type) :: protoTree
type(sdr_temData_type) :: temData
Call graph
seeder calls sdr_addtimers, sdr_build_prototree, sdr_dump_treelm, sdr_dumptimers, sdr_flood_tree, sdr_inherit_distancerefineobject, sdr_init_global, sdr_load_config, sdr_proto2treelm, sdr_refine_leaf, sdr_smooth_leaf, sdr_write_proto_as_restart, tem_finalize, tem_start, tem_stopTimer