name: Compilation and Unit Tests

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

jobs:
  compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Seeder
        uses: apes-suite/build-action@v1.1.1
        with:
          waf-args: "configure build debug"
